name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        toolchain:
          - stable
          # minimum version
          - "1.73"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust ${{ matrix.toolchain }}
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --component rustfmt,clippy --target wasm32-unknown-unknown
          rustup default ${{ matrix.toolchain }}

      - name: Check rustfmt
        run:
          cargo fmt --all -- --check

      - name: Build
        run: |
          cargo build --release

      - name: Test
        run: |
          cargo test --release

      - name: Build (example)
        run: |
          cd examples/yew-nested-router-example
          cargo build --release
